### ISSUE TITLE
Add support for ESLint 8.0

### ISSUE THREAD

**Issue by jpoehnelt** [wikimedia/eslint-docgen#126]
`eslint.CLIEngine` was removed in ESLint 8.0.0. ~Not sure what other changes are required.~ 

https://eslint.org/docs/8.0.0/user-guide/migrating-to-8.0.0#remove-cliengine

https://github.com/wikimedia/eslint-docgen/blob/fa53ec11e33ab92e010a09fb3e617e8e8e3524a5/src/fix.js#L5

**Update**

This codepath can be bypassed with 

```json
{
  "fixCodeExamples": false
}
```

I had no other issues with ESLint >= 8.0.0.

**Comment by jdforrester** [comment]
Fixed by #128. Sorry, just saw this! It'll be a breaking change release however.
